name: Data Request
description: Request a data collection to be made available to FAIRiCUBE use cases
title: "[Data Request]: "
labels: ["data-request"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide the information requested below. Mandatory elements are marked with `*`.
  - type: markdown
    attributes:
      value: |-
        # General
  - type: input
    id: id
    attributes:
      label: ID
      description: Datacube or collection identifier 
      placeholder: |-
        Example: Windspeed
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief, nontechnical explanation of the datacube
      placeholder: A timeseries of atmospheric wind speed over Europe
    validations:
      required: true
  - type: textarea
    id: project-purpose
    attributes:
      label: Project purpose 
      description: Description of the reason for collection/generation in relation to the project/WP/Task objectives. Why and how is theis data collection useful?
      placeholder: TBD
    validations:
      required: false
  - type: dropdown
    id: preferred-platform
    attributes:
      label: Preferred Platform
      multiple: true
      options:
        - EOxHub
        - Rasdaman
        - Other
- type: markdown
    attributes:
      value: |-
        # Datacube structure
  - type: textarea
    id: axes
    attributes:
      label: Axes
      description: Enumerate all axes of the datacube and their description 
      placeholder: |-
        Lat, Long: horizontal extent in WGS84; regular, resolution: XXX, uom: degree 
        t: time in days; regular, resolution: 1 day, uom: day 
        plev: pressure level, such as “FL100” expressed as 10000; irregular, uom: FL 
    validations:
      required: false
  - type: textarea
    id: cell-type
    attributes:
      label: Cell type
      description: What does each pixel/voxel represent? Indicate meaning, data type, and unit of measure
      placeholder: |-
        wind_u: East/West wind component, data type: uint16, uom: W/m^2 
        wind_v: North/South wind component, data type: uint16, uom: W/m^2 
    validations:
      required: false
  - type: input
    id: null-values
    attributes:
      label: Null values
      description: Set of values which express "data unavailable", "data unknown", etc.
      placeholder: 9999, NaN
    validations:
      required: false
  - type: input
    id: standards
    attributes:
      label: (Meta) data Standards
      description: Standards data complies with
      placeholder: OGC CIS
    validations:
      required: false
  - type: markdown
    attributes:
      value: |-
        # Datacube access
  - type: input
    id: apis
    attributes:
      label: APIs
      description: Access interfaces through which datacube can be accessed
      placeholder: OGC WMS, WMTS, WCS, WCPS, API Coverages, API Processes, etc.
    validations:
      required: false
  - type: input
    id: access-control
    attributes:
      label: Access control
      description: Security measures and policies applied
      placeholder: Login-protected, access only for FAIRiCUBE beneficiaries
    validations:
      required: false
  - type: markdown
    attributes:
      value: |-
        # Curator
  - type: input
    id: responsible
    attributes:
      label: Responsible
      description: Beneficiary name, contact(s)
      placeholder: <organisation>, <name>, <email>, ORCID <id>
    validations:
      required: false
  - type: markdown
    attributes:
      value: |-
        # Data origin
  - type: input
    id: data-source
    attributes:
      label: Data Source
      description: Origin of the data (institution, etc.) including download URL / email as appropriate where the data can be found
      placeholder: DWD
    validations:
      required: false
  - type: input
    id: data-preprocessing
    attributes:
      label: Data Preprocessing
      description: Brief description of what processing data have undergone to get into the datacube
      placeholder: Extracted from DWD-provided zip-compressed GRIB2
    validations:
      required: false
  - type: input
    id: quality-control
    attributes:
      label: Quality Control
      description: Describe any quality measures (standardised calibration, repeated samples or measurements, data capture, data entry validation, peer review of data, or representation with controlled vocabularies)
      placeholder: None in particular, DWD data are used as is
    validations:
      required: false
  - type: input
    id: documents-publications 
    attributes:
      label: Documents & publications 
      description: List related publications / public deliverables, state DOI and/or permanent location
      placeholder: TBD
    validations:
      required: false
  - type: markdown
    attributes:
      value: |-
        # Legal
  - type: input
    id: license
    attributes:
      label: License
      description: Such as Creative Commons CC BY 4.0 / Open Data Commons ODC-BY20 / Creative Commons BY NC 4.021
      placeholder: CC-BY-NC on RAS side, but constrained by DWD
    validations:
      required: false
  - type: input
    id: ownership
    attributes:
      label: Ownership
      description: IPR, Ownership (including 3rd party, citizen participation)
      placeholder: RAS/DWD
    validations:
      required: false
  - type: input
    id: personal-data 
    attributes:
      label: Personal Data 
      description: |-
        Confirm either:  
        No personal data is present in the dataset 
        Personal data is present, managed in compliance with GDPR 
        If (b), describe measures taken to secure, protect and/or pseudoanonymise / anonymise data. Notify the Project DPO if an issue arises. 
      placeholder: No personal data are captured in this datacube 
    validations:
      required: false
  - type: markdown
    attributes:
      value: |-
        # Other
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Any additional information that might be relevant
      placeholder:
    validations:
      required: false
