name: Validate generated stac item in the PR

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
      - '!master'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: |
          pip install --break-system-packages -r ./stac/stac-generator/requirements.txt
      - name: validate stac items

        run: |
          pytest --tb=no  ./stac/stac-generator/test/validator.py
